version: '3.7'

services:
  mariadb:
    image: mariadb:10.5.8-focal
    env_file:
      - ./.env
    volumes:
      - ./.docker/mysql/init/:/docker-entrypoint-initdb.d/
      - ./data/mysql
    ports:
      - "3308:3306"
  web:
    build: .
    command: bash -c "python manage.py makemigrations --settings biostar.forum.settings && python manage.py migrate --settings biostar.forum.settings && python manage.py runserver 0.0.0.0:8000 --settings biostar.forum.settings"
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - mariadb
    links:
      - mariadb
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
