- name: server backup
  shell: "./backup.sh"
  become: yes
  args:
    executable: /bin/bash
    chdir: "{{ engine_dir }}"

- name: stop supervisor
  become: yes
  service:
    name: supervisor
    state: stopped

- name: server reset
  shell: "./reset.sh"
  args:
    executable: /bin/bash
    chdir: "{{ engine_dir }}"

- name: init sciprts
  become: yes
  copy:
    remote_src: true
    force: no
    src: "{{ engine_dir }}//themes/bioconductor/conf/scripts/{{item}}"
    dest: "{{ engine_dir }}/{{ item }}"
    mode: u+rwx,g+rx,o+rx
  with_items:
    - migrate.sh
    - reset.sh
    - backup.sh
    -
- name: update git
  become: yes
  git:
    repo: "{{ engine_git }}"
    dest: "{{ engine_dir }}"
    update: yes

- name: server migrate
  shell: "./migrate.sh"
  args:
    executable: /bin/bash
    chdir: "{{ engine_dir }}"

- name: restart server
  become: yes
  shell: supervisorctl restart forum

- name: reload supervisor
  become: yes
  service:
    name: supervisor
    state: reloaded

- name: restart supervisor
  become: yes
  service:
    name: supervisor
    state: restarted

- name: start supervisor
  become: yes
  service:
    name: supervisor
    state: started

- name: restart nginx
  become: yes
  service: name=nginx state=restarted

- name: restart postgresql
  become: yes
  service:
    name: nginx
    state: restarted

