- name: server backup
  shell: "./backup.sh"
  args:
    executable: /bin/bash
    chdir: "{{ scripts_dir }}"

- name: stop supervisor
  become: yes
  service:
    name: supervisor
    state: stopped

- name: server reset
  become: yes
  shell: "./reset.sh"
  args:
    executable: /bin/bash
    chdir: "{{ scripts_dir }}"

- name: server migrate
  become: yes
  shell: "./migrate.sh"
  args:
    executable: /bin/bash
    chdir: "{{ scripts_dir }}"

- name: restart server
  become: yes
  shell: supervisorctl restart forum

- name: reload supervisor
  become: yes
  service:
    name: supervisor
    state: reloaded

- name: restart supervisor
  become: yes
  service:
    name: supervisor
    state: restarted

- name: start supervisor
  become: yes
  service:
    name: supervisor
    state: started

- name: restart nginx
  become: yes
  service: name=nginx state=restarted

- name: restart postgresql
  become: yes
  service:
    name: nginx
    state: restarted

