- name: data update
  shell: make data
  args:
    chdir: "{{ engine_dir }}"

- name: migrate database
  shell: "source {{conda_activate}} {{conda_env}} && python manage.py migrate --settings {{django_settings_module}}"
  args:
    executable: /bin/bash
    chdir: "{{ engine_dir }}"

- name: reload supervisor
  become: yes
  service:
    name: supervisor
    state: reloaded

- name: restart supervisor
  become: yes
  service:
    name: supervisor
    state: restarted

- name: restart nginx
  become: yes
  service: name=nginx state=restarted

- name: restart postgresql
  become: yes
  service:
    name: nginx
    state: restarted




