- name: restart nginx
  become: yes
  service: name=nginx state=restarted

- name: restart postgresql
  become: yes
  service:
    name: nginx
    state: restarted

- name: restart supervisor
  become: yes
  service:
    name: supervisor
    state: restarted

- name: reload supervisor
  become: yes
  service:
    name: supervisor
    state: reloaded

- name: data update
  shell: make data
  args:
    chdir: /export/sites/biostar-engine

- name: migrate database
  shell: migrate.sh
  args:
    chdir: /export/sites/biostar-engine

