- name: Update the biostar-engine
  git:
    repo: "{{ engine_git }}"
    dest: "{{ engine_dir }}"
    update: yes
  notify:
    - engine python install
    - server migrate
    - reload supervisor
    - restart nginx



