- name: Get the biostar-engine software
  git:
    repo: 'git@github.com:biostars/biostar-engine.git'
    dest: "{{ engine_dir }}"
    update: yes
  notify:
    - run migration
    - reload supervisor
    - restart nginx

- name: Get the biostar-recipes
  git:
    repo: 'git@github.com:biostars/biostar-recipes.git'
    dest: "{{ recipe_dir }}"
    update: yes

- name: Install dependencies
  shell: ls
  notify:
    - pip install
    - recipe install
    - conda install
    - update data
    - run migration
  when: install_recipes

- name: Make the spooler directory
  file:
    path: "{{ engine_dir }}/export/spooler"
    state: directory
    mode: 0755

- name: Initialize local secrets
  copy:
    content: ""
    dest: "{{ engine_dir }}/conf/site/site_secrets.py"
    force: no
    mode: 0644

- name: Initialize migration script
  copy:
    remote_src: true
    force: no
    src: "{{ engine_dir }}/conf/ansible/migrate.sh"
    dest: "{{ engine_dir }}/migrate.sh"
    mode: u+rwx,g+rx,o+rx
