- name: Get the biostar-engine software
  git:
    repo: "{{ engine_git }}"
    dest: "{{ engine_dir }}"
    update: yes
  notify:
    - engine python install
    - run migration
    - reload supervisor
    - restart nginx

- name: Get the biostar-recipes
  git:
    repo: "{{ recipe_git }}"
    dest: "{{ recipe_dir }}"
    update: yes

- name: Install dependencies
  shell: ls
  notify:
    - recipe python install
    - update data
    - run migration
  when: install

- name: Restart servers
  shell: ls
  notify:
    - reload supervisor
    - restart nginx
  when: restart

- name: Reset data
  shell: "source {{ conda_activate }} {{conda_env}}  && make reset"
  args:
    executable: /bin/bash
    chdir: "{{ engine_dir }}"
  notify:
    - reload supervisor
    - restart nginx
  when: reset


- name: Make the spooler directory
  file:
    path: "{{ engine_dir }}/export/spooler"
    state: directory
    mode: 0755

- name: Initialize local secrets
  copy:
    content: ""
    dest: "{{ engine_dir }}/conf/site/site_secrets.py"
    force: no
    mode: 0644

- name: Initialize migration script
  copy:
    remote_src: true
    force: no
    src: "{{ engine_dir }}/conf/ansible/migrate.sh"
    dest: "{{ engine_dir }}/migrate.sh"
    mode: u+rwx,g+rx,o+rx
