- name: Backup servers
  shell: ls
  notify:
    - server backup

- name: Update the biostar-engine
  git:
    repo: "{{ engine_git }}"
    dest: "{{ engine_dir }}"
    update: yes
  notify:
    - server migrate
    - reload supervisor
    - restart nginx

- name: Migrate servers
  shell: ls
  notify:
    - server migrate
  when: migrate


- name: Restart servers
  shell: ls
  notify:
    - reload supervisor
    - restart nginx
  when: restart

