- name: Get the biostar-engine software
  git:
    repo: "{{ engine_git }}"
    dest: "{{ engine_dir }}"
    update: yes
  notify:
    - engine python install
    - run migration
    - reload supervisor
    - restart nginx

- name: Get the biostar-recipes
  git:
    repo: "{{ recipe_git }}"
    dest: "{{ recipe_dir }}"
    update: yes

- name: Install dependencies
  shell: ls
  notify:
    - recipe python install
    - update data
    - server migrate
  when: install

- name: Restart servers
  shell: ls
  notify:
    - reload supervisor
    - restart nginx
  when: restart

- name: Reset all
  shell: "ls"
  args:
    executable: /bin/bash
    chdir: "{{ engine_dir }}"
  notify:
    - stop supervisor
    - server reset
    - server migrate
    - start supervisor
    - restart nginx
  when: reset

- name: Initialize migration script
  copy:
    remote_src: true
    force: no
    src: "{{ engine_dir }}/conf/scripts/{{item}}"
    dest: "{{ engine_dir }}/{{ item }}"
    mode: u+rwx,g+rx,o+rx
  with_items:
    - server_migrate.sh
    - setver_reset.sh
