- name: Update the biostar-engine
  git:
    repo: "{{ engine_git }}"
    dest: "{{ engine_dir }}"
    update: yes
  notify:
    - engine python install
    - server migrate
    - reload supervisor
    - restart nginx

- name: Update the biostar-recipes
  git:
    repo: "{{ recipe_git }}"
    dest: "{{ recipe_dir }}"
    update: yes

- name: Install dependencies
  shell: ls
  notify:
    - recipe python install
    - update data
    - server migrate
  when: install

- name: Restart servers
  shell: ls
  notify:
    - reload supervisor
    - restart nginx
  when: restart

- name: Reset engine
  shell: "ls"
  args:
    executable: /bin/bash
    chdir: "{{ engine_dir }}"
  notify:
    - stop supervisor
    - server reset
    - server migrate
    - restart supervisor
    - restart nginx
  when: reset

