- name: engine python install
  shell: "source {{ conda_activate }} {{conda_env}} && pip install -r conf/pip_requirements.txt"
  args:
    executable: /bin/bash
    chdir: "{{ engine_dir }}"

- name: recipe python install
  shell: "source {{ conda_activate }} {{conda_env}} && python setup.py develop"
  args:
    executable: /bin/bash
    chdir: "{{ recipe_dir }}"

- name: engine conda install
  shell: "source {{ conda_activate }} {{conda_env}}  && conda install --file conf/conda_requirements.txt"
  args:
    executable: /bin/bash
    chdir: "{{ engine_dir }}"

- name: recipe conda install
  shell: "source {{ conda_activate }} {{conda_env}}  && conda install --file conf/conda_requirements.txt"
  args:
    executable: /bin/bash
    chdir: "{{ recipe_dir }}"

- name: stop supervisor
  become: yes
  service:
    name: supervisor
    state: stopped

- name: server reset
  shell: "./server-reset.sh"
  args:
    executable: /bin/bash
    chdir: "{{ engine_dir }}"

- name: server migrate
  shell: "./server-migrate.sh"
  args:
    executable: /bin/bash
    chdir: "{{ engine_dir }}"

- name: update data
  shell: make data
  args:
    chdir: "{{ engine_dir }}"

- name: update projects
  shell: make projects
  args:
    chdir: "{{ engine_dir }}"

- name: restart server
  become: yes
  shell: supervisorctl restart engine

- name: reload supervisor
  become: yes
  service:
    name: supervisor
    state: reloaded

- name: restart supervisor
  become: yes
  service:
    name: supervisor
    state: restarted

- name: start supervisor
  become: yes
  service:
    name: supervisor
    state: started

- name: restart nginx
  become: yes
  service: name=nginx state=restarted

- name: restart postgresql
  become: yes
  service:
    name: nginx
    state: restarted

