
- name: Set up bash profile
  get_url:
    url: http://data.biostarhandbook.com/install/bash_profile.txt
    dest: ~/.bash_profile
    mode: 0440

- name: Get bashrc from remote
  get_url:
    url: http://data.biostarhandbook.com/install/bashrc.txt
    dest: ~/.handbookrc
    mode: 0440

- name: Apply the biostar bash customizations
  lineinfile:
    dest: ~/.bashrc
    line: source ~/.handbookrc

- name: Check if conda has already been installed
  stat: path={{ conda_home }}/bin/conda
  register: bin_conda
  changed_when: bin_conda.stat.exists == False

- name: Download conda installer
  get_url:
    url={{ conda_url }}
    dest=/tmp/conda.sh
    mode=0755
  register: conda_downloaded
  when: bin_conda.stat.exists == False

- name: Install conda
  shell: "/tmp/conda.sh -b -p {{ conda_home }} creates={{ conda_home }} executable=/bin/bash"
  register: conda_installed
  when: conda_downloaded | success
  notify:
    - Remove conda setup script
    - Update conda to latest version

- name: Add conda to the PATH
  lineinfile:
    dest: "{{ conda_rcfile }}"
    line: export PATH={{ conda_home }}/bin:$PATH
    state: present
  when: conda_modify_path

- name: Create environments
  shell: "{{ conda_home }}/bin/conda create --yes -q -n {{ item.name }} python={{ item.python_version }} creates={{ conda_home }}/envs/{{ item.name }}"
  when: conda_installed | success
  with_items: "{{conda_environments}}"

- name: Get the biostar-engine software
  git:
    repo: "{{ engine_git }}"
    dest: "{{ engine_dir }}"
    update: yes

- name: Make the spooler directory
  file:
    path: "{{ engine_dir }}/export/spooler"
    state: directory
    mode: 0755

- name: Initialize local secrets
  copy:
    content: ""
    dest: "{{ engine_dir }}/conf/site/site_secrets.py"
    force: no
    mode: 0644

- name: Get the biostar-recipes
  git:
    repo: "{{ recipe_git }}"
    dest: "{{ recipe_dir }}"
    update: yes

- name: Initialize scripts
  copy:
    remote_src: true
    force: no
    src: "{{ engine_dir }}/conf/scripts/{{item}}"
    dest: "{{ engine_dir }}/{{ item }}"
    mode: u+rwx,g+rx,o+rx
  with_items:
    - server_migrate.sh
    - server_reset.sh
