- name: Update apt-cache
  apt:
    upgrade=yes
    update_cache=yes
    cache_valid_time=86400 # One day

- name: Add certbot repository
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present

- name: Create the bioinfo group
  group:
    name: bioinfo

- name: Create the www group
  group:
    name: www

- name: Create the www user
  user:
    name: www
    shell: /bin/bash
    groups: www, bioinfo, sudo

- name: Install required packages
  vars:
     packages: [ 'nginx', 'postgresql', 'software-properties-common', 'python-certbot-nginx',
      'curl', 'git', 'ufw', 'fail2ban', 'byacc', 'zlib1g-dev', 'cmake', 'build-essential',
      'libboost-iostreams-dev', 'bamtools', 'libbamtools-dev', 'ncurses-dev', 'supervisor', 'python-psycopg2' ]
  apt: name={{ item }} state=latest
  with_items: "{{ packages }}"

- name: Allow SSH through the firewall
  ufw: rule=allow port={{item}}
  with_items:
   - ssh
   - http
   - https

- name: Enable firewall
  ufw: state=enabled policy=deny

- name: Create supporting directories
  file:
    path: "{{item}}"
    state: directory
    owner: www
    group: www
    mode: 0755
  with_items:
    - "{{ src_dir }}"
    - "{{ bin_dir }}"
    - "{{ ref_dir }}"
    - "{{ engine_dir }}"
    - "{{ recipe_dir }}"
    - "{{ data_dir }}"
    - "{{ data_dir }}/initial"

- name: Allow write access to configuration directories
  file:
    path: "{{ item }}"
    owner: www
    group: www
    mode: 0755
  with_items:
    - /etc/nginx/sites-enabled
    - /etc/supervisor/conf.d

- name: Create postgresql database user
  become: yes
  become_user: postgres
  postgresql_user:
    name: biostar_engine_user
    password: md5437a687918743dac1889ef033bcb5bbd
    role_attr_flags: CREATEDB,CREATEROLE

