
engine_git: https://github.com/ialbert/biostar-central.git
engine_dir:  "{{ main_dir | default('/export/www/biostar-central') }}"

bin_dir: "/export/bin"
src_dir: "/export/src"
ref_dir: "/export/refs"
local_dump : "{{ dump | 0 }}"
django_settings_module: "conf.run.site_settings"

# Installs recipe dependencies.
install: False
restart: False
reset: False


# Location to the old database in remote node
old_database: "{{ engine_dir }}/export/sql/old_biostar.sql.gz"

# Number of objects to limit when migration data over
transfer_limit: "{{ limit | default(100) }}"

conda_activate: "/home/www/miniconda3/envs/engine/bin/activate"
conda_env: "engine"

conda_url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
conda_dir: "~/miniconda3"

conda_environments:
  - { name: "{{ conda_env }}", python_version: 3.6}
  - { name: test, python_version: 3.6}
  - { name: py2, python_version: 2}

conda_modify_path: yes

conda_rcfile: "~/.bashrc"

conda_add_condarc: yes
