- name: Check if conda has already been installed
  stat: path={{ conda_home }}/bin/conda
  register: bin_conda
  changed_when: bin_conda.stat.exists == False

- name: Download conda installer
  get_url:
    url={{ conda_url }}
    dest=/tmp/conda.sh
    mode=0755
  register: conda_downloaded
  when: bin_conda.stat.exists == False

- name: Install conda
  shell: "/tmp/conda.sh -b -p {{ conda_home }} creates={{ conda_home }} executable=/bin/bash"
  register: conda_installed
  when: conda_downloaded | success
  notify:
    - Remove conda setup script
    - Update conda to latest version

- name: Add conda to the PATH
  lineinfile:
    dest: "{{ conda_rcfile }}"
    line: export PATH={{ conda_home }}/bin:$PATH
    state: present
  when: conda_modify_path

- name: Create environments
  shell: "{{ conda_home }}/bin/conda create --yes -q -n {{ item.name }} python={{ item.python_version }} creates={{ conda_home }}/envs/{{ item.name }}"
  when: conda_installed | success
  with_items: "{{conda_environments}}"


