
- name: Get the biostar-engine software
  git:
    repo: 'git@github.com:biostars/biostar-engine.git'
    dest: /export/sites/biostar-engine
    update: yes
  notify: engine install

- name: Get the biostar-recipes
  git:
    repo: 'git@github.com:biostars/biostar-recipes.git'
    dest: /export/sites/biostar-recipes
    update: yes
  notify: recipe install

- name: Make the spooler directory
  file:
    path: /export/sites/biostar-engine/export/spooler
    state: directory
    mode: 0755

- name: Initialize the migration script
  copy:
    remote_src: true
    src: /export/sites/biostar-engine/conf/ansible/migrate.sh
    dest: /export/sites/biostar-engine/migrate.sh
    mode: u+rwx,g+rx,o+rx

- name: Ensure local settings exists
  copy:
    content: ""
    dest: /export/sites/biostar-engine/conf/site/site_secrets.py
    force: no
    mode: 0644
