
- name: Set up bash profile
  get_url:
    url: http://data.biostarhandbook.com/install/bash_profile.txt
    dest: ~/.bash_profile
    mode: 0440

- name: Get bashrc from remote
  get_url:
    url: http://data.biostarhandbook.com/install/bashrc.txt
    dest: ~/.handbookrc
    mode: 0440

- name: Apply the biostar bash customizations
  lineinfile:
    dest: .bashrc
    line: source .handbookrc
