
- name: Get the biostar-engine software
  git:
    repo: 'git@github.com:biostars/biostar-engine.git'
    dest: /export/sites/biostar-engine
    update: yes
  notify: engine install

- name: Get the biostar-recipes
  git:
    repo: 'git@github.com:biostars/biostar-recipes.git'
    dest: /export/sites/biostar-recipes
    update: yes
  notify: recipe install

- name: Make the spooler directory
  file:
    path: /export/sites/main_web/export/spooler
    state: directory
    mode: 0755


