
- name: Set up bash profile
  get_url:
    url: http://data.biostarhandbook.com/install/bash_profile.txt
    dest: ~/.bash_profile
    mode: 0440

- name: Get bashrc from remote
  get_url:
    url: http://data.biostarhandbook.com/install/bashrc.txt
    dest: ~/.handbookrc
    mode: 0440

- name: Apply the biostar bash customizations
  lineinfile:
    dest: .bashrc
    line: source .handbookrc

- name: Check if miniconda has already been installed
  stat: path={{ miniconda_home }}/bin/conda
  register: bin_conda
  changed_when: bin_conda.stat.exists == False

- name: Download miniconda installer
  get_url:
    url={{ miniconda_url }}
    dest=/tmp/miniconda.sh
    mode=0755
  register: miniconda_downloaded
  when: bin_conda.stat.exists == False

- name: Install miniconda
  shell: "/tmp/miniconda.sh -b -p {{ miniconda_home }} creates={{ miniconda_home }} executable=/bin/bash"
  register: miniconda_installed
  when: miniconda_downloaded | success
  notify:
    - Remove miniconda setup script
    - Update conda to latest version

- name: Add miniconda to the PATH
  lineinfile:
    dest: "{{ miniconda_rcfile }}"
    line: export PATH={{ miniconda_home }}/bin:$PATH
    state: present
  when: miniconda_modify_path

- name: Clone the biostar-engine software
  git:
    repo: 'git@github.com:biostars/biostar-engine.git'
    dest: /export/sites/recipe_web

- name: Link NGINX config
  file:
    path: /export/sites/recipe_web
    state: directory
    owner: www
    group: www
    recurse: yes
