- name: Check if miniconda has already been installed
  stat: path={{ miniconda_home }}/bin/conda
  register: bin_conda
  changed_when: bin_conda.stat.exists == False

- name: Download miniconda installer
  get_url:
    url={{ miniconda_url }}
    dest=/tmp/miniconda.sh
    mode=0755
  register: miniconda_downloaded
  when: bin_conda.stat.exists == False

- name: Install miniconda
  shell: "/tmp/miniconda.sh -b -p {{ miniconda_home }} creates={{ miniconda_home }} executable=/bin/bash"
  register: miniconda_installed
  when: miniconda_downloaded | success
  notify:
    - Remove miniconda setup script
    - Update conda to latest version

- name: Add miniconda to the PATH
  lineinfile:
    dest: "{{ miniconda_rcfile }}"
    line: export PATH={{ miniconda_home }}/bin:$PATH
    state: present
  when: miniconda_modify_path

- name: Create environments
  shell: "{{ miniconda_home }}/bin/conda create --yes -q -n {{ item.name }} python={{ item.python_version }} creates={{ miniconda_home }}/envs/{{ item.name }}"
  when: miniconda_installed | success
  with_items: "{{miniconda_environments}}"



