
- name: Update apt-cache
  apt:
    upgrade=yes
    update_cache=yes
    cache_valid_time=86400 # One day

- name: Create the bioinfo group
  group:
    name: bioinfo

- name: Create the www user
  user:
    name: www
    shell: /bin/bash
    groups: www, bioinfo, sudo

- name: Install required packages
  vars:
     packages: [ 'nginx', 'postgresql', 'curl', 'git', 'ufw', 'fail2ban', 'byacc', 'zlib1g-dev', 'cmake', 'build-essential', 'ncurses-dev', 'supervisor' ]
  apt: name={{ item }} state=latest
  with_items: "{{ packages }}"

- name: Allow SSH through the firewall
  ufw: rule=allow port={{item}}
  with_items:
   - ssh
   - http
   - https

- name: Enable firewall
  ufw: state=enabled policy=deny

- name: Create recipe web directory
  file:
    path: /export/sites/recipe_web
    state: directory
    owner: www
    group: www
    mode: 0755

- name: Create recipe data directory
  file:
    path: /export/sites/recipe_data
    state: directory
    owner: www
    group: www
    mode: 0755

- name: Allow write access to Nginx directory
  file:
    path: /etc/nginx/sites-enabled
    owner: www
    group: www
    mode: 0755

- name: Allow write access to Supervisor directory
  file:
    path: /etc/supervisor/conf.d
    owner: www
    group: www
    mode: 0755
