
- name: Update apt-cache
  apt:
    upgrade=yes
    update_cache=yes
    cache_valid_time=86400 # One day

- name: Add certbot repository
  apt_repository:
    repo: 'ppa:certbot/certbot'
    state: present

- name: Create the bioinfo group
  group:
    name: bioinfo

- name: Create the www user
  user:
    name: www
    shell: /bin/bash
    groups: www, bioinfo, sudo

- name: Install required packages
  vars:
     packages: [ 'nginx', 'postgresql', 'software-properties-common', 'python-certbot-nginx',
      'curl', 'git', 'ufw', 'fail2ban', 'byacc', 'zlib1g-dev', 'cmake', 'build-essential', 'libboost-iostreams-dev',
      'ncurses-dev', 'supervisor' ]
  apt: name={{ item }} state=latest
  with_items: "{{ packages }}"

- name: Allow SSH through the firewall
  ufw: rule=allow port={{item}}
  with_items:
   - ssh
   - http
   - https

- name: Enable firewall
  ufw: state=enabled policy=deny

- name: Create file directories
  file:
    path: "/export/sites/{{item}}"
    state: directory
    owner: www
    group: www
    mode: 0755
  with_items:
    - main_web
    - main_data
    - main_data/initial

- name: Allow write access to configuration directories
  file:
    path: "{{ item }}"
    owner: www
    group: www
    mode: 0755
  with_items:
    - /etc/nginx/sites-enabled
    - /etc/supervisor/conf.d

